vich_uploader:
    db_driver: orm

    mappings:
        fileUpload:
            uri_prefix: /assets/files
            upload_destination: '%kernel.project_dir%/public/assets/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
