<?php

namespace ContainerL7e69sQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TYKojH3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tYKojH3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tYKojH3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contact' => ['privates', '.errored..service_locator.tYKojH3.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.tYKojH3": it references class "App\\Entity\\Contact" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'contact' => 'App\\Entity\\Contact',
            'em' => '?',
        ]);
    }
}
