<?php

namespace ContainerL7e69sQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploadTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FileUploadType' shared autowired service.
     *
     * @return \App\Form\FileUploadType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FileUploadType.php';

        return $container->privates['App\\Form\\FileUploadType'] = new \App\Form\FileUploadType();
    }
}
