<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEoC31Yy\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEoC31Yy/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerEoC31Yy.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerEoC31Yy\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerEoC31Yy\App_KernelProdContainer([
    'container.build_hash' => 'EoC31Yy',
    'container.build_id' => '0e6fb6a3',
    'container.build_time' => 1597935406,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEoC31Yy');
