<?php

namespace ContainerXJpxdlw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1QV4DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._1_qV4D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._1_qV4D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'file' => ['privates', '.errored..service_locator._1_qV4D.App\\Entity\\FileUpload', NULL, 'Cannot autowire service ".service_locator._1_qV4D": it references class "App\\Entity\\FileUpload" but no such service exists.'],
            'filesystem' => ['services', 'filesystem', 'getFilesystemService', true],
        ], [
            'em' => '?',
            'file' => 'App\\Entity\\FileUpload',
            'filesystem' => '?',
        ]);
    }
}
