<?php

namespace ContainerXJpxdlw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BICivRDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BICivRD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BICivRD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', false],
            'user' => ['privates', '.errored..service_locator.BICivRD.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.BICivRD": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'em' => '?',
            'mailer' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
