<?php

namespace ContainerEoC31Yy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploadService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator._1_qV4D.App\Entity\FileUpload' shared service.
     *
     * @return \App\Entity\FileUpload
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._1_qV4D": it references class "App\\Entity\\FileUpload" but no such service exists.');
    }
}
